# Generated by Django 5.2.3 on 2025-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_grade_schedule_student_related_student_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='related',
            new_name='subject',
        ),
    ]
