# Generated by Django 5.2.3 on 2025-06-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_related_teacher_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='related',
            new_name='class_name',
        ),
    ]
